[package]
name = "wp-specs"
version = "0.8.1"  # @gxl:set(version)
edition = "2024"
license = "Elastic-2.0"
description = "Ultra-light shared specs for WordPress Labs connectors and plugins"
readme = "README.md"
repository = "https://github.com/wp-labs/wp-specs"
homepage = "https://github.com/wp-labs/wp-specs"
documentation = "https://docs.rs/wp-specs"
keywords = ["wp-labs", "specs", "config", "serde", "wildcard"]
categories = ["config", "data-structures"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wildmatch = "2.6"
wp-connector-api = "0.8"

[dev-dependencies]
toml = "1.0"
